# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



pool:
  vmImage: 'ubuntu-latest'

steps:
- script: env | sort
  displayName: 'Run a one-line script'

- script: env | sort
  displayName: 'Run a one-line script'

- script: |
    dpkg --get-selections | grep -i php	
    sudo apt install libicu64 php7.4-intl
  displayName: 'Run a multi-line script'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
